// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_user_info.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserInfo = `-- name: UpdateUserInfo :one
update users
set
    email = $2,
    hashed_password = $3,
    updated_at = now()
where id = $1
returning id, email, hashed_password, created_at, updated_at, is_admin
`

type UpdateUserInfoParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserInfo, arg.ID, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}
